name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Check formatting with Prettier
        run: npm run format:check

      - name: Check formatting with EditorConfig
        run: npx eclint check "**/*.{js,json,yml,md}"

      - name: Run unit tests
        run: npm test

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run npm audit
        run: npm audit --production --audit-level=critical || true

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start server
        run: |
          npm start &
          echo "Waiting for server to be ready..."
          timeout 30s bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8432/health)" != "200" ]]; do sleep 1; done'
          echo "Server is ready!"

      - name: Test health endpoint
        run: |
          curl -f http://localhost:8432/health || exit 1

      - name: Test OpenAPI endpoint
        run: |
          curl -f http://localhost:8432/openapi.json || exit 1

      - name: Test format endpoint
        run: |
          echo "function test() { console.log('test'); }" > test.js
          curl -X POST http://localhost:8432/v1/tools/format_file \
            -H "Content-Type: application/json" \
            -d '{"file_path": "test.js"}' \
            -f || exit 1
